version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: 437-db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - 437-net

  backend:
    image: onrcanogul/437-api:latest
    build:
      args:
        ENABLE_DEBUG: "true"
    ports:
      - "8080:8080"
      - "5005:5005"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - 437-net
    environment:
      SPRING_PROFILES_ACTIVE: dev
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      AWS_SECRET_KEY: ${AWS_SECRET_KEY}
      AWS_REGION: ${AWS_REGION}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      AWS_ACCESS_KEY: ${AWS_ACCESS_KEY}
      S3_BUCKET_NAME: ${S3_BUCKET_NAME}
      ENCRYPTION_SECRET: ${ENCRYPTION_SECRET}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:

networks:
  437-net:
    driver: bridge
