spring:
  application:
    name: Starter-Template
  datasource:
    url: jdbc:postgresql://localhost:5432/demo_db
    username: demo_user
    password: demo_pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: YOUR_GOOGLE_CLIENT_ID
            client-secret: YOUR_GOOGLE_CLIENT_SECRET
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - openid
              - profile
              - email
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub
cloud:
  aws:
    region:
      static: eu-central-1
    credentials:
      access-key: ${AWS_ACCESS_KEY_ID}
      secret-key: ${AWS_SECRET_ACCESS_KEY}
    s3:
      bucket: meetingmindi-recordings

github:
  token: ghp_yourtoken
  repo:
    owner: yourusername
    name: yourrepository

azure:
  organization: your-org
  project: your-project
  pat: your-personal-access-token

jira:
  url: https://your-domain.atlassian.net
  email: your-email@example.com
  apiToken: your-jira-api-token
  projectKey: MINDI



secret-key: "SECRETKEYKEYKEKYEKYKEYKEYK3242352342efgdsfgsdfgdsfgds"
